"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import { EASE } from "@/lib/motion";

// IndustryShift — "The shift": real, verified public statements from the people
// building the frontier models, framed as INDUSTRY CONTEXT (never as
// endorsements of Noon). The arc: AI now writes much of the code (Amodei,
// Pichai) → but a human still reads, reviews and accepts what ships (Pichai's
// own words; vibe coding as the cautionary contrast) → that review is Noon's
// product. Each quote is attributed with name, role, source + date so it's
// verifiable. Hairline, single accent, reduced-motion-safe.

const VOICES: {
  quote: string;
  name: string;
  role: string;
  source: string;
  note?: string;
}[] = [
  {
    quote: "We're 3 to 6 months from a world where AI is writing 90% of the code.",
    name: "Dario Amodei",
    role: "CEO, Anthropic",
    source: "Council on Foreign Relations · 2025",
  },
  {
    quote:
      "Vibe coding — you fully give in to the vibes, embrace exponentials, and forget that the code even exists.",
    name: "Andrej Karpathy",
    role: "Founding member, OpenAI",
    source: "February 2025",
    note: "Fine for a weekend prototype. Not for what your business runs on.",
  },
];

export function IndustryShift() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section className="site-section">
      <div className="site-shell">
        <div ref={ref} className="mx-auto max-w-5xl">
          {/* eyebrow + headline */}
          <div className="max-w-2xl">
            <span className="site-meta-label inline-flex items-center gap-3 font-mono text-muted-foreground">
              <span className="h-px w-8 bg-foreground/30" />
              The shift
            </span>
            <h2 className="site-section-title mt-4">
              AI writes the code now. Someone still has to be sure.
            </h2>
            <p className="site-section-copy mt-3 text-muted-foreground">
              We don&apos;t hide that Noon builds with AI — and the people making the frontier
              models keep saying where this is going. Across every version, one thing holds: a
              human still reads, reviews, and accepts what ships.
            </p>
          </div>

          {/* hero quote — Pichai (the human-review clause is the whole point) */}
          <motion.figure
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.55, ease: EASE }}
            className="mt-9 border-l-2 border-primary/40 pl-6 lg:mt-12 lg:pl-8"
          >
            <blockquote className="text-[21px] font-medium leading-snug tracking-[-0.01em] text-foreground lg:text-[29px]">
              &ldquo;More than a quarter of all new code at Google is generated by AI, then{" "}
              <span className="text-primary">reviewed and accepted by engineers.</span>&rdquo;
            </blockquote>
            <figcaption className="mt-4 flex flex-wrap items-center gap-x-2.5 gap-y-1 text-sm">
              <span className="font-semibold text-foreground">Sundar Pichai</span>
              <span className="text-muted-foreground">CEO, Alphabet</span>
              <span className="font-mono text-[11px] text-muted-foreground/55">
                · Alphabet Q3 2024 earnings call
              </span>
            </figcaption>
          </motion.figure>

          {/* supporting voices — hairline grid */}
          <div className="mt-8 grid gap-px overflow-hidden rounded-[12px] border border-foreground/12 bg-foreground/10 sm:grid-cols-2 lg:mt-10">
            {VOICES.map((v, i) => (
              <motion.figure
                key={v.name}
                initial={{ opacity: 0, y: 12 }}
                animate={inView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, ease: EASE, delay: 0.12 + i * 0.08 }}
                className="flex flex-col bg-background p-6 lg:p-7"
              >
                <blockquote className="text-[15px] leading-relaxed text-foreground/90">
                  &ldquo;{v.quote}&rdquo;
                </blockquote>
                {v.note && (
                  <p className="mt-2.5 text-[12.5px] italic leading-snug text-muted-foreground/80">
                    {v.note}
                  </p>
                )}
                <figcaption className="mt-auto flex flex-wrap items-center gap-x-2 gap-y-0.5 pt-5 text-[13px]">
                  <span className="font-semibold text-foreground">{v.name}</span>
                  <span className="text-muted-foreground">{v.role}</span>
                  <span className="mt-0.5 w-full font-mono text-[10.5px] text-muted-foreground/50">
                    {v.source}
                  </span>
                </figcaption>
              </motion.figure>
            ))}
          </div>

          {/* bridge into the human-review proof that follows */}
          <p className="mt-8 max-w-2xl text-sm leading-relaxed text-muted-foreground lg:mt-10">
            <span className="font-medium text-foreground">
              Noon is built on the half that doesn&apos;t get automated.
            </span>{" "}
            Every build is AI-accelerated and signed off by a senior engineer, line by line — which
            is exactly what comes next.
          </p>
        </div>
      </div>
    </section>
  );
}
