export const countries = [
  "Afghanistan", "Albania", "Algeria", "Argentina", "Armenia", "Australia",
  "Austria", "Azerbaijan", "Bahrain", "Bangladesh", "Belarus", "Belgium",
  "Bolivia", "Bosnia and Herzegovina", "Brazil", "Bulgaria", "Cambodia",
  "Canada", "Chile", "China", "Colombia", "Costa Rica", "Croatia", "Cuba",
  "Czech Republic", "Denmark", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Estonia", "Ethiopia", "Finland", "France", "Georgia",
  "Germany", "Ghana", "Greece", "Guatemala", "Honduras", "Hungary",
  "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kuwait", "Latvia",
  "Lebanon", "Libya", "Lithuania", "Luxembourg", "Malaysia", "Mexico",
  "Morocco", "Myanmar", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
  "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Panama",
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
  "Romania", "Russia", "Saudi Arabia", "Senegal", "Serbia", "Singapore",
  "Slovakia", "Slovenia", "South Africa", "South Korea", "Spain",
  "Sri Lanka", "Sweden", "Switzerland", "Taiwan", "Thailand", "Tunisia",
  "Turkey", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
  "United States", "Uruguay", "Uzbekistan", "Venezuela", "Vietnam",
  "Zimbabwe",
] as const;

/**
 * Business tax-ID label per country, aligned with Stripe's `tax_id` types (so the
 * label the client sees matches what Stripe collects once wired). Countries Stripe
 * doesn't enumerate fall back to a generic "Tax ID".
 */
const TAX_ID_LABELS: Record<string, string> = {
  Argentina: "CUIT",
  Australia: "ABN",
  Austria: "VAT ID",
  Belgium: "VAT ID",
  Bolivia: "NIT",
  Brazil: "CNPJ",
  Bulgaria: "VAT ID",
  Canada: "GST/HST number",
  Chile: "RUT",
  Colombia: "NIT",
  Croatia: "VAT ID",
  "Czech Republic": "VAT ID",
  Denmark: "VAT ID",
  "Dominican Republic": "RCN",
  Ecuador: "RUC",
  "El Salvador": "NIT",
  Estonia: "VAT ID",
  Finland: "VAT ID",
  France: "VAT ID",
  Georgia: "VAT",
  Germany: "VAT ID",
  Greece: "VAT ID",
  Hungary: "VAT ID",
  India: "GSTIN",
  Indonesia: "NPWP",
  Ireland: "VAT ID",
  Israel: "VAT",
  Italy: "VAT ID",
  Japan: "Corporate Number",
  Kenya: "KRA PIN",
  Latvia: "VAT ID",
  Lithuania: "VAT ID",
  Luxembourg: "VAT ID",
  Malaysia: "SST number",
  Mexico: "RFC",
  Netherlands: "VAT ID",
  "New Zealand": "GST number",
  Norway: "VAT number",
  Paraguay: "RUC",
  Peru: "RUC",
  Philippines: "TIN",
  Poland: "NIP",
  Portugal: "VAT ID",
  Romania: "VAT ID",
  Russia: "INN",
  "Saudi Arabia": "VAT",
  Serbia: "PIB",
  Singapore: "GST/UEN",
  Slovakia: "VAT ID",
  Slovenia: "VAT ID",
  "South Africa": "VAT number",
  "South Korea": "BRN",
  Spain: "NIF",
  Sweden: "VAT ID",
  Switzerland: "VAT number",
  Taiwan: "VAT",
  Thailand: "VAT",
  Turkey: "Tax ID",
  Ukraine: "VAT",
  "United Arab Emirates": "TRN",
  "United Kingdom": "VAT number",
  "United States": "EIN",
  Uruguay: "RUC",
  Venezuela: "RIF",
};

export function taxIdLabel(country: string): string {
  return TAX_ID_LABELS[country] ?? "Tax ID";
}
