/**
 * lib/maxwell/deterministic-assets.ts
 *
 * Fase A · E3.4 — NIVEL 2 de la cascada (spec §6): "deterministas, coste
 * cero". They cost nothing, never rate-limit, and never come back empty —
 * which is why they sit between the paid search and the last resort.
 *
 * Two providers, both chosen because their output is PREDICTABLE:
 *
 *   - Illustrated avatars (DiceBear's documented public API). Owner's rule
 *     is hard here: avatars only in PLAYFUL families. In a premium family
 *     a cartoon face where a portrait belongs is worse than no image at
 *     all, so this returns nothing there.
 *   - Section/hero backgrounds, generated by us as SVG data URIs tinted
 *     from the family's own palette. Generated rather than hotlinked on
 *     purpose: an asset we compose cannot 404, cannot drift, and cannot
 *     put a third party inside the client's page.
 *
 * Deliberately NOT here: placeholder B2B logos. The spec names Logoipsum,
 * but its asset URLs are not a documented API and inventing URL patterns
 * would ship broken images — the one thing the imagery rules forbid
 * outright. It stays a gap until the source is verified.
 */

import type { StockImage } from "@/lib/server/stock-images";
import type { ShotSpec } from "./creative-order";
import type { StylePack } from "./style-packs";

/** Families whose tone genuinely fits illustrated faces. */
const PLAYFUL_FAMILIES = new Set([
  "playful-consumer",
  "kids-education",
  "pets-veterinary",
  "events-social",
]);

/** DiceBear styles that read as friendly rather than gimmicky. */
const AVATAR_STYLES = ["notionists", "adventurer", "open-peeps"] as const;

/**
 * Stable pseudo-random from a string: same slot always yields the same
 * face, so a re-run does not reshuffle the team page.
 */
function seedFrom(text: string): number {
  let hash = 0;
  for (let i = 0; i < text.length; i++) hash = (hash * 31 + text.charCodeAt(i)) >>> 0;
  return hash;
}

function avatarFor(slot: ShotSpec, index: number): StockImage {
  const seed = seedFrom(`${slot.slotId}:${slot.subject}:${index}`);
  const style = AVATAR_STYLES[seed % AVATAR_STYLES.length];
  const url = `https://api.dicebear.com/9.x/${style}/svg?seed=${encodeURIComponent(String(seed))}&backgroundType=solid`;
  return { url, urlLarge: url, alt: slot.subject || "Illustrated avatar", avgColor: null };
}

/** A calm, tinted background composed from the family's own palette. */
function backgroundFor(slot: ShotSpec, pack: StylePack): StockImage {
  const { bg, ink, accent } = pack.token.palette;
  const seed = seedFrom(`${slot.slotId}:${pack.id}`);
  const angle = 25 + (seed % 110);
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900" preserveAspectRatio="xMidYMid slice">` +
    `<defs><linearGradient id="g" gradientTransform="rotate(${angle})">` +
    `<stop offset="0%" stop-color="${bg}"/>` +
    `<stop offset="65%" stop-color="${bg}"/>` +
    `<stop offset="100%" stop-color="${accent}" stop-opacity="0.18"/>` +
    `</linearGradient></defs>` +
    `<rect width="1600" height="900" fill="url(#g)"/>` +
    `<circle cx="${200 + (seed % 900)}" cy="${180 + (seed % 420)}" r="${180 + (seed % 160)}" fill="${ink}" opacity="0.04"/>` +
    `</svg>`;
  const url = `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
  return { url, urlLarge: url, alt: `${pack.name} background`, avgColor: bg };
}

/**
 * Candidates for a slot from the deterministic level. Empty when this
 * level has nothing HONEST to offer for that slot — an empty slot beats a
 * wrong asset, and the brief already tells v0 to use typography there.
 */
export function deterministicCandidates(params: {
  slot: ShotSpec;
  stylePack: StylePack;
  count?: number;
}): StockImage[] {
  const { slot, stylePack, count = 2 } = params;

  if (slot.role === "portrait") {
    if (!PLAYFUL_FAMILIES.has(stylePack.id)) return [];
    return Array.from({ length: count }, (_, index) => avatarFor(slot, index));
  }

  if (slot.role === "background") {
    return [backgroundFor(slot, stylePack)];
  }

  // Heroes and sections carry the product's promise — a generated shape is
  // not a substitute for a real photograph of the real thing.
  return [];
}
